### ISSUE TITLE
Google Drive folder support

### ISSUE THREAD

**Issue by windhamwong** [niqdev/packtpub-crawler#6]
Hello, I love your script and I would like to ask for an extra feature!
Putting files into a folder on Google Drive would be much better and tidier.
Here is the reference of the Python code:
https://developers.google.com/drive/v3/web/folder#creating_a_folder

If you have no time to do it and you don't mind me to make a pull request, I am happy to help.

**Comment by niqdev** [comment]
I'm glad you like it! Yes sure, if you want to make a pull request you are welcome!
I like the idea, I didn't think about it because I have a dedicated account just for this, but it's a good enhancement.
The only thing that I can suggest is to add the name/path of the directory in the config file with a default like `packtpub`, so every body can choose the name that prefer and automatically create the directory if doesn't exist.
If you need any help let me know!

**Comment by windhamwong** [comment]
Added pull request.
https://github.com/niqdev/packtpub-crawler/pull/7

**Comment by niqdev** [comment]
It works like a charm! Thank you!
